### ISSUE TITLE
Brak zdjęcia w sekcji dodatkow w menu

### ISSUE THREAD

**Issue by ForkersCDV** [DeveloperCDV/PizzeriaCDV#7]
Hej, widzę, że nie ma obrazka do sekcji dodatki, reszta je ma. Sprawdzicie to?

**Comment by DeveloperCDV** [comment]
Rzeczywiście, już dodajemy! Zobacz tutaj: f8a0626

**Comment by DeveloperCDV** [comment]
f8a0626 fixes #7
